### ISSUE TITLE
Eerie will not install.

### ISSUE THREAD

**Issue by Raynes** [josip/eerie#2] opened 2010-03-23 21:01 UTC
rayne@rayne-desktop:~/eerie$ io setup.io 
---- Installing Eerie ----
- Updated bash profile.
- Updated iorc file.
  
  > ln -s /home/rayne/.eerie/env/_base /home/rayne/.eerie/activeEnv
  > ln -s /home/rayne/.eerie/env/_base /home/rayne/.eerie/base
  > cp -R /home/rayne/eerie/ /home/rayne/.eerie/env/_base/addons/Eerie
  ## Exception: Don't know how to install package at /home/rayne/.eerie/env/_base/addons/Eerie
  
  Exception raise                      PackageInstaller.io 29
  PackageInstaller detect              Package.io 88
  Package setInstaller                 Package.io 88
  Package install                      setup.io 57
  Object setup                         setup.io 68

**Comment by josip** [comment] 2010-03-23 21:06
I can't reproduce it on my computer, could you tell which OS you are using and which Io version you have installed?

**Comment by Raynes** [comment] 2010-03-23 21:09
I'm using Ubuntu Hardy. Io 'version'? Since when are there 'versions'? :p I'm using the latest version of the git repo. Pulled it this morning.

**Comment by josip** [comment] 2010-03-23 21:31
Haha, true, maybe git commit id would be more appropriate :)
Looks like it isn't working for me either on Fedora (it works on OSX, tough). I'll look into this.

**Comment by josip** [comment] 2010-03-23 22:40
Fixed install issue on Linux. Closed by cad0485a988b9cad58713884c2ff7b43a8929d4d.

The problem was in `cp`, on OSX/BSD if source path has trailing slash it is same as:  `cp -r something/* somewhere/`, this trick appears to be unsupported in GNU version of  `cp`.

**Closed as completed by josip** 2010-03-23 22:40 UTC
